### ISSUE TITLE
Where is ../code/output/development_split.csv folder?

### ISSUE THREAD

**Issue by minducky** [fgnt/sed_scores_eval#3]
Where is [../code/output/development_split.csv] file in extract_features.py ?

**Comment by JanekEbb** [comment]
Hi, I think you opened the issue in the wrong repo. Probably you wanted to put it [here](https://github.com/marmoi/dcase2023_task4b_baseline), didn't you?

**Comment by minducky** [comment]
Oh, I'm sorry.

I thought I opened the issue in&nbsp;here https://github.com/marmoi/dcase2023_task4b_baseline, but I took a mistake.

I'll issue on there again.

Thanks&nbsp;

민덕기&nbsp;MIN, DEOKKI
기계공학과-석사&nbsp;/&nbsp;석사
34141 대전광역시 유성구 대학로 291 한국과학기술원(KAIST)Email&nbsp; ***@***.*** ***@***.***



-----Original Message-----
