### ISSUE TITLE
the error to use the package

### ISSUE THREAD

**Issue by paozhuanis1** [fgnt/sed_scores_eval#7]
when I use the package to compute psds scores, I was confronted with the error, which is 

> 发生异常: ImportError
> numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
>   File "/mnt/lcy/fdy/utils/evaluation_v23.py", line 1, in <module>
>     import sed_scores_eval
>   File "/mnt/lcy/fdy/main_gc.py", line 471, in <module>
>     from utils.evaluation_v23 import v23_compute_psds_from_sed_scores_eval
> ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

I am wandering if the improper version of the numpy causes this error. If so, which version of the numpy is correct.

Thank you for your early reply!!!

**Comment by JanekEbb** [comment]
Is that the complete traceback? Looks like most of it refers to your local file structure. Can you share the complete traceback you get from only calling `import sed_scores_eval`?
